---
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install yamllint==1.19.0 flake8
  pre_build:
    commands:
      - yamllint *.yml .yamllint .s8/*.yml
      - flake8 lambda.py
  build:
    commands:
      - zip -r lambda.zip ./

artifacts:
  files:
    - cloudformation.yml
    - lambda.zip
